apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: basic-users-access
  namespace: demo-system
rules:
- apiGroups: ["basic.authn.krateo.io"]
  resources: ["users"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: basic-users-access-binding
  namespace: demo-system
subjects:
- kind: ServiceAccount
  name: authn
  namespace: demo-system
roleRef:
  kind: Role
  name: basic-users-access
  apiGroup: rbac.authorization.k8s.io
