name: Label PR Based on Commit Messages

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags

      - name: Fetch main branch
        run: |
          # Fetch the main branch to ensure it is available for comparison
          git fetch origin main:main

      - name: Fetch all commits for the PR
        run: |
          # Check out the PR branch and compare commits against main
          commits=$(git log main..HEAD --pretty=format:"%s")
          echo "Commits: $commits"

          # Initialize labels as an array
          LABELS=()

          # Check commit messages and set labels
          if [[ "$commits" =~ feat ]]; then
            LABELS+=("enhancement")
          fi
          if [[ "$commits" =~ fix ]]; then
            LABELS+=("bug")
          fi
          if [[ "$commits" =~ chore ]]; then
            LABELS+=("chore")
          fi
          if [[ "$commits" =~ build ]]; then
            LABELS+=("build")
          fi
          if [[ "$commits" =~ ci ]]; then
            LABELS+=("ci")
          fi
          if [[ "$commits" =~ docs ]]; then
            LABELS+=("documentation")
          fi
          if [[ "$commits" =~ perf ]]; then
            LABELS+=("perf")
          fi
          if [[ "$commits" =~ refactor ]]; then
            LABELS+=("refactor")
          fi
          if [[ "$commits" =~ revert ]]; then
            LABELS+=("revert")
          fi
          if [[ "$commits" =~ style ]]; then
            LABELS+=("style")
          fi
          if [[ "$commits" =~ test ]]; then
            LABELS+=("test")
          fi

          # Convert the labels array to a JSON string
          LABELS_JSON=$(printf '%s\n' "${LABELS[@]}" | jq -R . | jq -s .)
          echo "Labels to add: $LABELS_JSON"

          # Export labels as an environment variable
          echo "LABELS=$LABELS_JSON" >> $GITHUB_ENV


      - name: Add labels to PR using REST API
        if: env.LABELS != '[]'
        run: |
          curl -s -X POST \
            -H "Authorization: token ${{ secrets.ADD_LABEL_ON_PULL_REQUEST }}" \
            -H "Content-Type: application/json" \
            --data "{\"labels\": $LABELS}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/labels"
